apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: default
spec:
  commonName: inpulsetech.io
  secretName: homepage-cert
  dnsNames:
    - inpulsetech.io
    - www.inpulsetech.io
  issuerRef:
    name: letsencrypt
    kind: Issuer
