---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`inpulsetech.io`) || Host(`www.inpulsetech.io`)
      kind: Rule
      services:
        - name: homepage
          port: 8080
      middlewares:
        - name: hsts-header
          namespace: default
  tls:
    secretName: homepage-cert

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-http-redirect
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`inpulsetech.io`) || Host(`www.inpulsetech.io`)
      kind: Rule
      services:
        - name: homepage
          port: 8080
      middlewares:
        - name: https-redirectscheme
          namespace: default
        - name: hsts-header
          namespace: default
